apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  accessModes: {{ .Values.pvc.accessModes }}
  resources:
    requests:
      storage: {{ .Values.pvc.storageRequest | quote }}
  storageClassName: {{ .Values.pvc.storageClass | quote }}
  volumeName: nfs