{{- if .Values.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  accessModes: {{ .Values.accessModes }}
  resources:
    requests:
      storage: {{ .Values.storageRequest | quote }}
  storageClassName: {{ .Values.storageClass | quote }}
{{- end }}