apiVersion: v2
name: charts-box-parent
description: A Helm chart for Kubernetes

type: application
version: 0.0.1

dependencies:
  - name: deployment
    version: 0.0.1
    repository: file://../charts/deployment/