deployment:
  deploymentValues:
    image:
      repository: ""
      pullPolicy: Always
      tag:
    volumeMounts:
      mountPath: ""

  service:
    name: ""
    ports:
      name: http
      protocol: TCP
      port: 5002
      targetPort: 5002
    type: ClusterIP

  persistentVolumeClaim:
    # -- enable persistent-volu
    enabled: false
    # -- set access mode for pe
    accessModes:
      - ReadWriteMany
    # -- set storage class
    storageClass: "nfs-client"
    # -- set desired size for p
    storageRequest: 1Mi

  configmap:
    enabled: false

  virtual_service:
    enabled: true
    name:
    namespace: istio-system
    gateways: ""
    hosts: ""
    http:
      route:
        destination:
          host: ""
          port:
            number: 5002




