{{- define "deploymentLibrary.configmap" -}}
{{- if .Values.deployment.configmap.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.deployment.service.name}}
  labels:
  {{- include "chart.labels" . | nindent 4 }}
data:
  config.yaml: |

{{- end -}}
{{- end -}}